# 行列積の実装

以下のような行列A、Bを考えます。

NumPyで表すと次のようになります。

import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])


## 【問題1】行列積を手計算する

AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。



回答

-1 × 0 + 2 × 0  + 3 × 2 = 6

-1 × 2 + 2 × 2  + 3 × 9 = 29

-1 × 1 + 2 × -8 + 3 × -1 = -20

4 × 0 + -5 × 0  + 6 × 2 = 12

4 × 2 + -5 × 2  + 6 × 9 = 52

4 × 1 + -5 × -8 + 6 × -1 = 38

7 × 2 + 8 × 0 + -9 × 2 = -18

7 × 2 + 8 × 2 + -9 × 9 = -51

7 × 1 + 8 × -8 + -9 × -1 = -48

## 【問題2】NumPyの関数による計算

この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。


これらを使い行列積を計算してください。


numpy.matmul — NumPy v1.16 Manual


numpy.dot — NumPy v1.16 Manual


**《3種類の違い》**


np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。


今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。


If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.


3.行列積のスクラッチ実装

In [33]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# 回答
print(np.matmul(a_ndarray,b_ndarray))
print(np.dot(a_ndarray,b_ndarray))
a1 = -1 * 0 + 2 * 0  + 3 * 2 
a2 = -1 * 2 + 2 * 2  + 3* 9
a3 = -1 * 1 + 2 * -8 + 3 * -1
a4 = 4 * 0 + -5 * 0  + 6 * 2
a5 = 4 * 2 + -5 * 2  + 6 * 9 
a6 = 4 * 1 + -5 * -8 + 6 * -1 
a7 = 7 * 0 + 8 * 0 + -9 * 2
a8 = 7 * 2 + 8 * 2 + -9 * 9
a9 = 7 * 1 + (8 * -8) + (-9 * -1)  # -48

print(np.array([[a1,a2,a3],[a4,a5,a6],[a7,a8,a9]]))


[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### 行列積のスクラッチ実装

np.matmul()やnp.dot()、または@演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。

これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。



## 【問題3】ある要素の計算を実装

手計算をする際はまず行列Aの0行目と行列Bの0列目に注目し、以下の計算を行ったかと思います。


行列Aの(0,0)の要素 
a
0
,
0
 と行列Bの(0,0)の要素 
b
0
,
0
 を掛け合わせる
 
 
行列Aの(0,1)の要素 
a
0
,
1
 と行列Bの(1,0)の要素 
b
1
,
0
 を掛け合わせる
 
 
行列Aの(0,2)の要素 
a
0
,
2
 と行列Bの(2,0)の要素 
b
2
,
0
 を掛け合わせる
 
 
それらの値をすべて足し合わせる

この計算をnp.matmul()やnp.dot()、または@演算子を使わずに行うコードを書いてください。

In [129]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], 
                                        [4, -5, 6],
                                        [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1],
                                        [0, 2, -8], 
                                        [2, 9, -1]])

calc_1 = a_ndarray[0,0]*b_ndarray[0,0]+a_ndarray[0,1]*b_ndarray[1,0]+a_ndarray[0,2]*b_ndarray[2,0]
calc_2 = a_ndarray[0,0]*b_ndarray[0,1]+a_ndarray[0,1]*b_ndarray[1,1]+a_ndarray[0,2]*b_ndarray[2,1]
calc_3 = a_ndarray[0,0]*b_ndarray[0,2]+a_ndarray[0,1]*b_ndarray[1,2]+a_ndarray[0,2]*b_ndarray[2,2]

calc_4 = a_ndarray[1,0]*b_ndarray[0,0]+a_ndarray[1,1]*b_ndarray[1,0]+a_ndarray[1,2]*b_ndarray[2,0]
calc_5 = a_ndarray[1,0]*b_ndarray[0,1]+a_ndarray[1,1]*b_ndarray[1,1]+a_ndarray[1,2]*b_ndarray[2,1]
calc_6 = a_ndarray[1,0]*b_ndarray[0,2]+a_ndarray[1,1]*b_ndarray[1,2]+a_ndarray[1,2]*b_ndarray[2,2]

calc_7 = a_ndarray[2,0]*b_ndarray[0,0]+a_ndarray[2,1]*b_ndarray[1,0]+a_ndarray[2,2]*b_ndarray[2,0]
calc_8 = a_ndarray[2,0]*b_ndarray[0,1]+a_ndarray[2,1]*b_ndarray[1,1]+a_ndarray[2,2]*b_ndarray[2,1]
calc_9 = a_ndarray[2,0]*b_ndarray[0,2]+a_ndarray[2,1]*b_ndarray[1,2]+a_ndarray[2,2]*b_ndarray[2,2]
print(calc_1)
print(calc_2)
print(calc_3)

print(calc_4)
print(calc_5)
print(calc_6)

print(calc_7)
print(calc_8)
print(calc_9)

6
29
-20
12
52
38
-18
-51
-48


## 【問題4】行列積を行う関数の作成
問題3のコードを拡張し、行列積のスクラッチ実装を完成させてください。行列AとBを引数に受け取り、行列積を返す関数としてください。


行列積を計算する場合は、問題3の計算を異なる行や列に対して繰り返していくことになります。


計算結果である $3 \times 3$ の行列Cの各要素 $c_{i, j}$ は数式で表すと次のようになります。


c
i
,
j
=
2
∑
k
=
0
 
a
i
,
k
b
k
,
j

for文を使い、ndarrayのインデックスを動かしていくことで、合計9つの要素が計算できます。インデックス $i$ や $j$ を1増やすと、次の行や列に移ることができます。


Image from Gyazo


**4.行列積が定義されない組み合わせの行列**

次に以下のような例を考えます。


D
=
[
−
1
2
3
4
−
5
6
]
,
E
−
=
[
−
9
8
7
6
−
5
4
]

1
2
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

行列積DEはDの列数とEの行数が等しい場合に定義されていますから、この例では計算ができません。



In [123]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], 
                                        [4, -5, 6],
                                        [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1],
                                        [0, 2, -8], 
                                        [2, 9, -1]])

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

def queue_calc(a_ndarray,b_ndarray):
    ''' 引数にndarrayを渡すと行列積の結果を返してくれる関数（３×３）
    Paramenters
    ----------------
    a_ndarray
        ndarray（行）
    b_ndarray
        ndarray（列）
    
    Return
    ----------------
    行列積の結果
        calc_1, calc_2, calc_3,
        calc_4, calc_5, calc_6,
        calc_7, calc_8, calc_9
    '''
    calc_1 = a_ndarray[0,0]*b_ndarray[0,0]+a_ndarray[0,1]*b_ndarray[1,0]+a_ndarray[0,2]*b_ndarray[2,0]
    calc_2 = a_ndarray[0,0]*b_ndarray[0,1]+a_ndarray[0,1]*b_ndarray[1,1]+a_ndarray[0,2]*b_ndarray[2,1]
    calc_3 = a_ndarray[0,0]*b_ndarray[0,2]+a_ndarray[0,1]*b_ndarray[1,2]+a_ndarray[0,2]*b_ndarray[2,2]

    calc_4 = a_ndarray[1,0]*b_ndarray[0,0]+a_ndarray[1,1]*b_ndarray[1,0]+a_ndarray[1,2]*b_ndarray[2,0]
    calc_5 = a_ndarray[1,0]*b_ndarray[0,1]+a_ndarray[1,1]*b_ndarray[1,1]+a_ndarray[1,2]*b_ndarray[2,1]
    calc_6 = a_ndarray[1,0]*b_ndarray[0,2]+a_ndarray[1,1]*b_ndarray[1,2]+a_ndarray[1,2]*b_ndarray[2,2]

    calc_7 = a_ndarray[2,0]*b_ndarray[0,0]+a_ndarray[2,1]*b_ndarray[1,0]+a_ndarray[2,2]*b_ndarray[2,0]
    calc_8 = a_ndarray[2,0]*b_ndarray[0,1]+a_ndarray[2,1]*b_ndarray[1,1]+a_ndarray[2,2]*b_ndarray[2,1]
    calc_9 = a_ndarray[2,0]*b_ndarray[0,2]+a_ndarray[2,1]*b_ndarray[1,2]+a_ndarray[2,2]*b_ndarray[2,2]

    return calc_1,calc_2,calc_3,calc_4,calc_5,calc_6,calc_7,calc_8,calc_9

print(queue_calc(a_ndarray,b_ndarray))

(6, 29, -20, 12, 52, 38, -18, -51, -48)


## 【問題5】計算が定義されない入力を判定する

問題4で作成した関数は、実装方法によってはこのDとEの配列を入力しても動いてしまう可能性があります。

この場合、不適切な計算が行われることになります。

また、途中でエラーになる場合でも、なぜエラーになったかが直接的には分かりづらいメッセージが表示されます。


if文などによってこれを防ぎ、入力される形に問題があることをprint()を使い表示するコードを書き加えてください。

In [125]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], 
                                        [4, -5, 6],
                                        [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1],
                                        [0, 2, -8], 
                                        [2, 9, -1]])


def queue_calc(a_ndarray,b_ndarray):
    ''' 引数にndarrayを渡すと行列積の結果を返してくれる関数（３×３）
    Paramenters
    ----------------
    a_ndarray
        ndarray（行）
    b_ndarray
        ndarray（列）
    
    Return
    ----------------
    行列積の結果
        calc_1, calc_2, calc_3,
        calc_4, calc_5, calc_6,
        calc_7, calc_8, calc_9
    '''
    # もし配列の中身が３×３ならば、行列積を行う
    if [len(v) for v in a_ndarray] == [len(v) for v in b_ndarray] :
        calc_1 = a_ndarray[0,0]*b_ndarray[0,0]+a_ndarray[0,1]*b_ndarray[1,0]+a_ndarray[0,2]*b_ndarray[2,0]
        calc_2 = a_ndarray[0,0]*b_ndarray[0,1]+a_ndarray[0,1]*b_ndarray[1,1]+a_ndarray[0,2]*b_ndarray[2,1]
        calc_3 = a_ndarray[0,0]*b_ndarray[0,2]+a_ndarray[0,1]*b_ndarray[1,2]+a_ndarray[0,2]*b_ndarray[2,2]

        calc_4 = a_ndarray[1,0]*b_ndarray[0,0]+a_ndarray[1,1]*b_ndarray[1,0]+a_ndarray[1,2]*b_ndarray[2,0]
        calc_5 = a_ndarray[1,0]*b_ndarray[0,1]+a_ndarray[1,1]*b_ndarray[1,1]+a_ndarray[1,2]*b_ndarray[2,1]
        calc_6 = a_ndarray[1,0]*b_ndarray[0,2]+a_ndarray[1,1]*b_ndarray[1,2]+a_ndarray[1,2]*b_ndarray[2,2]

        calc_7 = a_ndarray[2,0]*b_ndarray[0,0]+a_ndarray[2,1]*b_ndarray[1,0]+a_ndarray[2,2]*b_ndarray[2,0]
        calc_8 = a_ndarray[2,0]*b_ndarray[0,1]+a_ndarray[2,1]*b_ndarray[1,1]+a_ndarray[2,2]*b_ndarray[2,1]
        calc_9 = a_ndarray[2,0]*b_ndarray[0,2]+a_ndarray[2,1]*b_ndarray[1,2]+a_ndarray[2,2]*b_ndarray[2,2]
    else:
        print("要素数の合わない組み合わせのため、計算できません")

    return calc_1,calc_2,calc_3,calc_4,calc_5,calc_6,calc_7,calc_8,calc_9

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

# 回答
print(queue_calc(a_ndarray,b_ndarray))
print(queue_calc(d_ndarray,a_ndarray))

(6, 29, -20, 12, 52, 38, -18, -51, -48)
要素数の合わない組み合わせのため、計算できません


UnboundLocalError: local variable 'calc_1' referenced before assignment

## 【問題6】転置

片方の行列を転置することで、行列積が計算できるようになります。


np.transpose()や.Tアトリビュートを用いて転置し、行列積を計算してください。

In [128]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], 
                                        [4, -5, 6],
                                        [7, 8, -9]])

b_ndarray = np.array([[0, 2, 1],
                                        [0, 2, -8], 
                                        [2, 9, -1]])


def queue_calc(a_ndarray,b_ndarray):
    ''' 引数にndarrayを渡すと行列積の結果を返してくれる関数（３×３）
    Paramenters
    ----------------
    a_ndarray
        ndarray（行）
    b_ndarray
        ndarray（列）
    
    Return
    ----------------
    行列積の結果
        calc_1, calc_2, calc_3,
        calc_4, calc_5, calc_6,
        calc_7, calc_8, calc_9
    '''
    # もし配列の中身が３×３ならば、行列積を行う
    if [len(v) for v in a_ndarray] == [len(v) for v in b_ndarray] :
        calc_1 = a_ndarray[0,0]*b_ndarray[0,0]+a_ndarray[0,1]*b_ndarray[1,0]+a_ndarray[0,2]*b_ndarray[2,0]
        calc_2 = a_ndarray[0,0]*b_ndarray[0,1]+a_ndarray[0,1]*b_ndarray[1,1]+a_ndarray[0,2]*b_ndarray[2,1]
        calc_3 = a_ndarray[0,0]*b_ndarray[0,2]+a_ndarray[0,1]*b_ndarray[1,2]+a_ndarray[0,2]*b_ndarray[2,2]

        calc_4 = a_ndarray[1,0]*b_ndarray[0,0]+a_ndarray[1,1]*b_ndarray[1,0]+a_ndarray[1,2]*b_ndarray[2,0]
        calc_5 = a_ndarray[1,0]*b_ndarray[0,1]+a_ndarray[1,1]*b_ndarray[1,1]+a_ndarray[1,2]*b_ndarray[2,1]
        calc_6 = a_ndarray[1,0]*b_ndarray[0,2]+a_ndarray[1,1]*b_ndarray[1,2]+a_ndarray[1,2]*b_ndarray[2,2]

        calc_7 = a_ndarray[2,0]*b_ndarray[0,0]+a_ndarray[2,1]*b_ndarray[1,0]+a_ndarray[2,2]*b_ndarray[2,0]
        calc_8 = a_ndarray[2,0]*b_ndarray[0,1]+a_ndarray[2,1]*b_ndarray[1,1]+a_ndarray[2,2]*b_ndarray[2,1]
        calc_9 = a_ndarray[2,0]*b_ndarray[0,2]+a_ndarray[2,1]*b_ndarray[1,2]+a_ndarray[2,2]*b_ndarray[2,2]
    else:
        print("要素数の合わない組み合わせのため、計算できません")

    return calc_1,calc_2,calc_3,calc_4,calc_5,calc_6,calc_7,calc_8,calc_9

# 回答
a_ndarray = np.transpose(a_ndarray)
print(queue_calc(a_ndarray,b_ndarray))


(14, 69, -40, 16, 66, 34, -18, -63, -36)
